packages:
  - 'apps/*'
  - 'prisma'
  - 'quick-chat-*'

autoInstallPeers: true
ignoredBuiltDependencies:
  - '@scarf/scarf'
  - '@sentry/node-cpu-profiler'
  - bcrypt
  - esbuild

onlyBuiltDependencies:
  - nx
  - '@prisma/engines'
  - prisma
